/**
 * Generates src/auth.ts, boilauth.config.ts and src/permissions.ts from answers.
 * Only modules the answers switched on are imported.
 */
import type { Answers } from "../wizard/answers.js";

const HEADER = "// Generated by `boilauth init` from boilauth.answers.json. Re-run init after changing answers.\n";

export function needsSessionPolicy(a: Answers): boolean {
  return a.session.devices === "single" || (a.signIn.emailPassword && a.session.revokeOnPasswordChange);
}

export function authFile(a: Answers): string {
  const pw = a.signIn.emailPassword;
  const bePlugins: string[] = [];
  const lines: string[] = [];
  const plugins: string[] = [];
  const rolesOn = a.roles.mode !== "none";

  if (rolesOn) bePlugins.push("admin");
  if (a.roles.mode === "custom") lines.push('import { ac, roles } from "./permissions.js";');
  if (a.roles.mode === "organizations") bePlugins.push("organization");
  if (a.signIn.magicLink) bePlugins.push("magicLink");
  if (pw && a.password.breachedCheck === "hibp") bePlugins.push("haveIBeenPwned");
  if (a.mfa.mode !== "off") bePlugins.push("twoFactor");

  if (a.roles.mode === "custom") plugins.push('admin({ ac, roles, adminRoles: ["admin"], defaultRole: "user" })');
  else if (rolesOn) plugins.push("admin()");
  if (a.roles.mode === "organizations") {
    const create = a.roles.orgCreation === "any_user" ? "true" : 'async (user) => (user as { role?: string }).role === "admin"';
    plugins.push(`organization({
      allowUserToCreateOrganization: ${create},
      sendInvitationEmail: async (data) =>
        d.email({ to: data.email, subject: "You are invited to " + data.organization.name, text: \`\${d.baseURL}/accept-invitation/\${data.id}\` }),
    })`);
  }
  if (a.signIn.magicLink) {
    plugins.push(`magicLink({ sendMagicLink: async ({ email, url }) => d.email({ to: email, subject: "Your sign-in link", text: url }) })`);
  }
  if (pw && a.password.breachedCheck === "hibp") plugins.push("haveIBeenPwned()");
  if (a.mfa.mode !== "off") plugins.push("twoFactor({ issuer: new URL(d.baseURL).hostname })");
  if (a.mfa.mode === "totp_required_admin") {
    lines.push('import { requireAdminMfa } from "boilauth/mfa";');
    plugins.push('requireAdminMfa({ adminRoles: ["admin"] })');
  }
  lines.push('import { accountDeletion } from "boilauth/deletion";');
  plugins.push(`accountDeletion({ mode: ${JSON.stringify(a.deletion.mode)}, exportData: ${a.deletion.export} })`);
  if (needsSessionPolicy(a)) {
    lines.push('import { sessionPolicy } from "boilauth/sessions";');
    // Last: must run after twoFactor's after-hook (see boilauth/sessions).
    plugins.push(
      `sessionPolicy({ devices: ${JSON.stringify(a.session.devices)}, revokeOnPasswordChange: ${pw && a.session.revokeOnPasswordChange} })`,
    );
  }

  const oauth = a.signIn.oauth;
  const oauthType = oauth.length
    ? `  /** Client credentials per provider, usually from env. */
  oauth: Record<${oauth.map((p) => JSON.stringify(p)).join(" | ")}, { clientId: string; clientSecret: string }>;\n`
    : "";
  const imports = [
    'import { createBoilAuth, type BoilAuthOptions, type EmailMessage } from "boilauth";',
    ...(bePlugins.length ? [`import { ${bePlugins.join(", ")} } from "better-auth/plugins";`] : []),
    ...lines,
  ].join("\n");

  const opts: string[] = [
    "database: d.database",
    "secret: d.secret",
    "baseURL: d.baseURL",
    `emailPassword: ${pw}`,
    "sendEmail: d.email",
    `requireEmailVerification: ${pw && a.email.verification === "required"}`,
    `rateLimitSignInPerMinute: ${a.rateLimit.signInPerMinute}`,
    `sessionDays: ${a.session.days}`,
  ];
  if (pw) {
    opts.push(`minPasswordLength: ${a.password.minLength}`);
    opts.push(`lockout: { maxFailures: ${a.lockout.maxFailures}, lockMinutes: ${a.lockout.minutes} }`);
  }
  if (a.migration.sources.includes("firebase")) opts.push("firebaseKeys: d.firebaseKeys");
  if (oauth.length) {
    opts.push(`accountLinking: ${JSON.stringify(a.linking.mode)}`);
    opts.push("socialProviders: d.oauth");
  }
  if (!rolesOn) opts.push("admin: false");
  const extraBetterAuth = oauth.includes("apple")
    ? '{ trustedOrigins: ["https://appleid.apple.com"], ...d.betterAuth }'
    : "d.betterAuth";
  opts.push(`plugins: [\n      ${plugins.join(",\n      ")},\n    ]`);
  opts.push(`betterAuth: ${extraBetterAuth}`);

  return `${HEADER}${imports}

export interface AuthDeps {
  database: BoilAuthOptions["database"];
  secret: string;
  baseURL: string;
  /** Sends verification, reset${a.signIn.magicLink ? ", magic link" : ""}${a.roles.mode === "organizations" ? ", invitation" : ""} mail. See src/email.ts. */
  email: (msg: EmailMessage) => Promise<void>;
${a.migration.sources.includes("firebase") ? '  firebaseKeys?: BoilAuthOptions["firebaseKeys"];\n' : ""}${oauthType}  betterAuth?: BoilAuthOptions["betterAuth"];
}

export function createAuth(d: AuthDeps) {
  return createBoilAuth({
    ${opts.join(",\n    ")},
  });
}

export type Auth = ReturnType<typeof createAuth>;
`;
}

const ENV_OAUTH: Record<string, string> = {
  google: "GOOGLE",
  github: "GITHUB",
  apple: "APPLE",
  kakao: "KAKAO",
  naver: "NAVER",
};

export function configFile(a: Answers): string {
  const db =
    a.runtime.database === "postgres"
      ? 'import pg from "pg";\n'
      : 'import { DatabaseSync } from "node:sqlite";\n';
  const dbExpr =
    a.runtime.database === "postgres"
      ? "new pg.Pool({ connectionString: need(\"DATABASE_URL\") })"
      : 'new DatabaseSync(process.env.BOILAUTH_SQLITE ?? "auth.db")';
  const fb = a.migration.firebase;
  const firebase = a.migration.sources.includes("firebase")
    ? `  firebaseKeys: process.env.FIREBASE_SIGNER_KEY
    ? [{ keyId: ${JSON.stringify(fb.keyId)}, signerKey: process.env.FIREBASE_SIGNER_KEY, saltSeparator: ${JSON.stringify(fb.saltSeparator)}, rounds: ${fb.rounds}, memCost: ${fb.memCost} }]
    : [],\n`
    : "";
  const oauth = a.signIn.oauth.length
    ? `  oauth: {\n${a.signIn.oauth
        .map((p) => `    ${p}: { clientId: need("${ENV_OAUTH[p]}_CLIENT_ID"), clientSecret: need("${ENV_OAUTH[p]}_CLIENT_SECRET") },`)
        .join("\n")}\n  },\n`
    : "";
  return `${HEADER}// The instance your app mounts and the boilauth CLI uses (--config boilauth.config.ts).
${db}import { createAuth } from "./src/auth.js";
import { sendEmail } from "./src/email.js";

function need(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(\`set \${name}\`);
  return v;
}

export default createAuth({
  database: ${dbExpr},
  secret: need("BOILAUTH_SECRET"),
  baseURL: process.env.BOILAUTH_URL ?? "http://localhost:3000",
  email: sendEmail,
${firebase}${oauth}});
`;
}

export function envExample(a: Answers): string {
  const lines = ["# openssl rand -base64 32", "BOILAUTH_SECRET=", "BOILAUTH_URL=http://localhost:3000"];
  if (a.runtime.database === "postgres") lines.push("DATABASE_URL=postgres://user:pass@localhost:5432/app", "# for tests: an empty scratch database", "TEST_DATABASE_URL=");
  else lines.push("BOILAUTH_SQLITE=auth.db");
  if (a.migration.sources.includes("firebase")) lines.push("# Firebase console > Authentication > Password hash parameters", "FIREBASE_SIGNER_KEY=");
  for (const p of a.signIn.oauth) lines.push(`${ENV_OAUTH[p]}_CLIENT_ID=`, `${ENV_OAUTH[p]}_CLIENT_SECRET=`);
  return lines.join("\n") + "\n";
}

export function permissionsFile(a: Answers): string {
  const extra = a.roles.custom.filter((r) => r !== "admin" && r !== "user");
  return `// Generated once by \`boilauth init\` (roles.mode = custom). Yours to edit: init leaves it alone once it exists.
// Statements are resource -> actions. Check with auth.api.userHasPermission(...).
import { createAccessControl } from "better-auth/plugins/access";
import { adminAc, defaultStatements, userAc } from "better-auth/plugins/admin/access";

export const statement = {
  ...defaultStatements,
  project: ["create", "read", "update", "delete"],
} as const;

export const ac = createAccessControl(statement);

export const roles = {
  admin: ac.newRole({ ...adminAc.statements, project: ["create", "read", "update", "delete"] }),
  user: ac.newRole({ ...userAc.statements, project: ["read"] }),
${extra.map((r) => `  ${JSON.stringify(r)}: ac.newRole({ project: ["read", "update"] }),`).join("\n")}
};
`;
}

export function emailFile(): string {
  return `// Generated once by \`boilauth init\`. Yours to edit: connect your mail provider here.
import type { EmailMessage } from "boilauth";

export async function sendEmail(msg: EmailMessage): Promise<void> {
  if (process.env.NODE_ENV === "production") {
    throw new Error("src/email.ts: connect a mail provider before production");
  }
  console.log(\`[email to \${msg.to}] \${msg.subject}\\n\${msg.text}\`);
}
`;
}
