/**
 * Generates src/auth.ts, boilauth.config.ts and src/permissions.ts from answers.
 * Only modules the answers switched on are imported.
 */
import type { Answers } from "../wizard/answers.js";

const HEADER = "// Generated by `boilauth init` from boilauth.answers.json. Re-run init after changing answers.\n";

export function needsSessionPolicy(a: Answers): boolean {
  return a.session.devices === "single" || (a.signIn.emailPassword && a.session.revokeOnPasswordChange);
}

/** The send endpoint the generated tests exercise, or null when the project sends no mail or SMS to a named address. */
export function sendEndpoint(a: Answers): { path: string; newDest: string; body: (d: string) => string } | null {
  if (a.signIn.emailPassword) return { path: "/request-password-reset", newDest: 'h.newEmail("rl")', body: (d) => `{ email: ${d} }` };
  if (a.signIn.magicLink) return { path: "/sign-in/magic-link", newDest: 'h.newEmail("rl")', body: (d) => `{ email: ${d}, callbackURL: "/" }` };
  if (a.signIn.emailOtp) return { path: "/email-otp/send-verification-otp", newDest: 'h.newEmail("rl")', body: (d) => `{ email: ${d}, type: "sign-in" }` };
  if (a.signIn.phone) return { path: "/phone-number/send-otp", newDest: "h.newPhone()", body: (d) => `{ phoneNumber: ${d} }` };
  return null;
}

/** boilauth/rate-limit is imported only when there is a send endpoint and a send limit is on. */
export function needsSendLimits(a: Answers): boolean {
  return sendEndpoint(a) !== null && (a.rateLimit.sendPerIpPerHour > 0 || a.rateLimit.sendPerAccountPerHour > 0);
}

export function authFile(a: Answers): string {
  const pw = a.signIn.emailPassword;
  const username = pw && a.signIn.username;
  const bePlugins: string[] = [];
  const lines: string[] = [];
  const plugins: string[] = [];
  const rolesOn = a.roles.mode !== "none";

  if (rolesOn) bePlugins.push("admin");
  if (a.roles.mode === "custom") lines.push('import { ac, roles } from "./permissions.js";');
  if (a.roles.mode === "organizations") bePlugins.push("organization");
  if (a.signIn.magicLink) bePlugins.push("magicLink");
  if (a.signIn.emailOtp) bePlugins.push("emailOTP");
  if (pw && a.password.breachedCheck === "hibp") bePlugins.push("haveIBeenPwned");
  if (a.mfa.mode !== "off") bePlugins.push("twoFactor");

  if (a.roles.mode === "custom") plugins.push('admin({ ac, roles, adminRoles: ["admin"], defaultRole: "user" })');
  else if (rolesOn) plugins.push("admin()");
  if (a.roles.mode === "organizations") {
    const create = a.roles.orgCreation === "any_user" ? "true" : 'async (user) => (user as { role?: string }).role === "admin"';
    plugins.push(`organization({
      allowUserToCreateOrganization: ${create},
      sendInvitationEmail: async (data) =>
        d.email({ to: data.email, subject: "You are invited to " + data.organization.name, text: \`\${d.baseURL}/accept-invitation/\${data.id}\` }),
    })`);
  }
  if (a.signIn.magicLink) {
    plugins.push(`magicLink({ sendMagicLink: async ({ email, url }) => d.email({ to: email, subject: "Your sign-in link", text: url }) })`);
  }
  if (a.signIn.emailOtp) {
    plugins.push(`emailOTP({
      otpLength: 6,
      expiresIn: 300,
      allowedAttempts: 3,
      storeOTP: "hashed",
      sendVerificationOTP: async ({ email, otp }) => d.email({ to: email, subject: "Your sign-in code", text: \`Your code is \${otp}. It expires in 5 minutes.\` }),
    })`);
  }
  if (pw && a.password.breachedCheck === "hibp") plugins.push("haveIBeenPwned()");
  if (a.mfa.mode !== "off") {
    const tf = ["issuer: new URL(d.baseURL).hostname"];
    if (a.mfa.backupCodes !== 10) tf.push(`backupCodeOptions: { amount: ${a.mfa.backupCodes} }`);
    if (a.mfa.emailOtp) {
      tf.push(`otpOptions: {
        digits: 6,
        period: 5,
        allowedAttempts: 3,
        storeOTP: "hashed",
        sendOTP: async ({ user, otp }) => d.email({ to: user.email, subject: "Your sign-in code", text: \`Your second-step code is \${otp}. It expires in 5 minutes.\` }),
      }`);
    }
    plugins.push(tf.length === 1 ? `twoFactor({ ${tf[0]} })` : `twoFactor({\n      ${tf.join(",\n      ")},\n    })`);
  }
  if (a.mfa.mode === "totp_required_admin") {
    lines.push('import { requireAdminMfa } from "boilauth/mfa";');
    plugins.push('requireAdminMfa({ adminRoles: ["admin"] })');
  }
  if (needsSendLimits(a)) {
    lines.push('import { sendLimits } from "boilauth/rate-limit";');
    plugins.push(`sendLimits({ perIpPerHour: ${a.rateLimit.sendPerIpPerHour}, perAccountPerHour: ${a.rateLimit.sendPerAccountPerHour} })`);
  }
  lines.push(`import { accountDeletion${a.deletion.guard ? ", type DeletionCheck" : ""} } from "boilauth/deletion";`);
  const del = [`mode: ${JSON.stringify(a.deletion.mode)}`, `exportData: ${a.deletion.export}`];
  if (a.deletion.records === "anonymize") del.push('records: "anonymize"');
  if (a.deletion.guard) del.push("canDelete: d.canDelete");
  if (a.roles.mode === "organizations") del.push(`organizations: { lastOwner: ${JSON.stringify(a.deletion.lastOrgOwner)} }`);
  plugins.push(`accountDeletion({ ${del.join(", ")} })`);
  if (needsSessionPolicy(a)) {
    lines.push('import { sessionPolicy } from "boilauth/sessions";');
    // Last: must run after twoFactor's after-hook (see boilauth/sessions).
    plugins.push(
      `sessionPolicy({ devices: ${JSON.stringify(a.session.devices)}, revokeOnPasswordChange: ${pw && a.session.revokeOnPasswordChange} })`,
    );
  }

  const oauth = a.signIn.oauth;
  const oauthType = oauth.length
    ? `  /** Client credentials per provider, usually from env. */
  oauth: Record<${oauth.map((p) => JSON.stringify(p)).join(" | ")}, { clientId: string; clientSecret: string }>;\n`
    : "";
  const imports = [
    `import { createBoilAuth, type BoilAuthOptions, type EmailMessage${a.signIn.phone ? ", type SmsMessage" : ""} } from "boilauth";`,
    ...(bePlugins.length ? [`import { ${bePlugins.join(", ")} } from "better-auth/plugins";`] : []),
    ...(username ? ['import type { UsernameRules } from "boilauth/username";'] : []),
    ...lines,
  ].join("\n");

  const opts: string[] = [
    "database: d.database",
    "secret: d.secret",
    "baseURL: d.baseURL",
    `emailPassword: ${pw}`,
    "sendEmail: d.email",
    `requireEmailVerification: ${pw && a.email.verification === "required"}`,
    `rateLimitSignInPerMinute: ${a.rateLimit.signInPerMinute}`,
    ...(a.rateLimit.storage === "memory" ? ['rateLimitStorage: "memory"'] : []),
    `sessionDays: ${a.session.days}`,
    `sessionAbsoluteDays: ${a.session.absoluteDays}`,
  ];
  if (a.network.clientIp === "proxy") opts.push(`clientIp: { mode: "proxy", trustedProxies: ${JSON.stringify(a.network.trustedProxies)} }`);
  if (a.network.clientIp === "header") opts.push(`clientIp: { mode: "header", header: ${JSON.stringify(a.network.clientIpHeader)} }`);
  if (pw) {
    opts.push(`minPasswordLength: ${a.password.minLength}`);
    opts.push(`lockout: { maxFailures: ${a.lockout.maxFailures}, lockMinutes: ${a.lockout.minutes}, accountMaxFailures: ${a.lockout.accountMaxFailures} }`);
  }
  if (a.migration.sources.includes("firebase")) opts.push("firebaseKeys: d.firebaseKeys");
  if (username) opts.push("username: d.usernameRules");
  if (a.signIn.phone) {
    const ph = ["sendSms: d.sms", `smsPerHour: ${a.rateLimit.smsPerHour}`];
    if (a.phone.allowedCountries.length) ph.push(`allowedCountryCodes: ${JSON.stringify(a.phone.allowedCountries)}`);
    opts.push(`phone: { ${ph.join(", ")} }`);
  }
  if (username) opts.push(`usernameCheckPerIpPerHour: ${a.rateLimit.usernameCheckPerIpPerHour}`);
  if (oauth.length) {
    opts.push(`accountLinking: ${JSON.stringify(a.linking.mode)}`);
    opts.push("socialProviders: d.oauth");
  }
  if (!rolesOn) opts.push("admin: false");
  else if (a.roles.hideAdmin) opts.push("hideAdminRoutes: true");
  if (a.session.bearer) opts.push("bearer: true");
  if (!a.notify.securityChanges || a.notify.newDevice) {
    const on = a.notify.securityChanges;
    opts.push(`securityNotices: { passwordChanged: ${on}, mfaChanged: ${on}, accountLocked: ${on}, newDevice: ${a.notify.newDevice && a.signIn.emailPassword} }`);
  }
  const extraBetterAuth = oauth.includes("apple")
    ? '{ trustedOrigins: ["https://appleid.apple.com"], ...d.betterAuth }'
    : "d.betterAuth";
  opts.push(`plugins: [\n      ${plugins.join(",\n      ")},\n    ]`);
  opts.push(`betterAuth: ${extraBetterAuth}`);

  return `${HEADER}${imports}

export interface AuthDeps {
  database: BoilAuthOptions["database"];
  secret: string;
  baseURL: string;
  /** Sends verification, reset${a.signIn.magicLink ? ", magic link" : ""}${a.signIn.emailOtp ? ", one-time code" : ""}${a.roles.mode === "organizations" ? ", invitation" : ""} mail. See src/email.ts. */
  email: (msg: EmailMessage) => Promise<void>;
${a.signIn.phone ? "  /** Sends SMS codes. See src/sms.ts. */\n  sms: (msg: SmsMessage) => Promise<void>;\n" : ""}${a.deletion.guard ? "  /** The app's veto on self-service deletion. See src/deletion-guard.ts. */\n  canDelete: DeletionCheck;\n" : ""}${a.migration.sources.includes("firebase") ? '  firebaseKeys?: BoilAuthOptions["firebaseKeys"];\n' : ""}${username ? "  /** boilauth.username.yaml, loaded with loadUsernameRules(). */\n  usernameRules: UsernameRules;\n" : ""}${oauthType}  betterAuth?: BoilAuthOptions["betterAuth"];
}

export function createAuth(d: AuthDeps) {
  return createBoilAuth({
    ${opts.join(",\n    ")},
  });
}

export type Auth = ReturnType<typeof createAuth>;
`;
}

const ENV_OAUTH: Record<string, string> = {
  google: "GOOGLE",
  github: "GITHUB",
  apple: "APPLE",
  kakao: "KAKAO",
  naver: "NAVER",
};

export function configFile(a: Answers): string {
  const db =
    a.runtime.database === "postgres"
      ? 'import pg from "pg";\n'
      : 'import { DatabaseSync } from "node:sqlite";\n';
  const dbExpr =
    a.runtime.database === "postgres"
      ? "new pg.Pool({ connectionString: need(\"DATABASE_URL\") })"
      : 'new DatabaseSync(process.env.BOILAUTH_SQLITE ?? "auth.db")';
  const fb = a.migration.firebase;
  const firebase = a.migration.sources.includes("firebase")
    ? `  firebaseKeys: process.env.FIREBASE_SIGNER_KEY
    ? [{ keyId: ${JSON.stringify(fb.keyId)}, signerKey: process.env.FIREBASE_SIGNER_KEY, saltSeparator: ${JSON.stringify(fb.saltSeparator)}, rounds: ${fb.rounds}, memCost: ${fb.memCost} }]
    : [],\n`
    : "";
  const oauth = a.signIn.oauth.length
    ? `  oauth: {\n${a.signIn.oauth
        .map((p) => `    ${p}: { clientId: need("${ENV_OAUTH[p]}_CLIENT_ID"), clientSecret: need("${ENV_OAUTH[p]}_CLIENT_SECRET") },`)
        .join("\n")}\n  },\n`
    : "";
  const username = a.signIn.emailPassword && a.signIn.username;
  const usernameImport = username ? 'import { loadUsernameRules } from "boilauth/username";\n' : "";
  const usernameDep = username ? '  usernameRules: loadUsernameRules(new URL("./boilauth.username.yaml", import.meta.url)),\n' : "";
  return `${HEADER}// The instance your app mounts and the boilauth CLI uses (--config boilauth.config.ts).
${db}${usernameImport}import { createAuth } from "./src/auth.js";
import { sendEmail } from "./src/email.js";${a.signIn.phone ? '\nimport { sendSms } from "./src/sms.js";' : ""}${a.deletion.guard ? '\nimport { canDelete } from "./src/deletion-guard.js";' : ""}

function need(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(\`set \${name}\`);
  return v;
}

export default createAuth({
  database: ${dbExpr},
  secret: need("BOILAUTH_SECRET"),
  baseURL: process.env.BOILAUTH_URL ?? "http://localhost:3000",
  email: sendEmail,
${a.signIn.phone ? "  sms: sendSms,\n" : ""}${a.deletion.guard ? "  canDelete,\n" : ""}${firebase}${usernameDep}${oauth}});
`;
}

export function envExample(a: Answers): string {
  const lines = ["# openssl rand -base64 32", "BOILAUTH_SECRET=", "BOILAUTH_URL=http://localhost:3000"];
  if (a.runtime.database === "postgres") lines.push("DATABASE_URL=postgres://user:pass@localhost:5432/app", "# for tests: an empty scratch database", "TEST_DATABASE_URL=");
  else lines.push("BOILAUTH_SQLITE=auth.db");
  if (a.migration.sources.includes("firebase")) lines.push("# Firebase console > Authentication > Password hash parameters", "FIREBASE_SIGNER_KEY=");
  for (const p of a.signIn.oauth) lines.push(`${ENV_OAUTH[p]}_CLIENT_ID=`, `${ENV_OAUTH[p]}_CLIENT_SECRET=`);
  return lines.join("\n") + "\n";
}

export function permissionsFile(a: Answers): string {
  const extra = a.roles.custom.filter((r) => r !== "admin" && r !== "user");
  return `// Generated once by \`boilauth init\` (roles.mode = custom). Yours to edit: init leaves it alone once it exists.
// Statements are resource -> actions. Check with auth.api.userHasPermission(...).
import { createAccessControl } from "better-auth/plugins/access";
import { adminAc, defaultStatements, userAc } from "better-auth/plugins/admin/access";

export const statement = {
  ...defaultStatements,
  project: ["create", "read", "update", "delete"],
} as const;

export const ac = createAccessControl(statement);

export const roles = {
  admin: ac.newRole({ ...adminAc.statements, project: ["create", "read", "update", "delete"] }),
  user: ac.newRole({ ...userAc.statements, project: ["read"] }),
${extra.map((r) => `  ${JSON.stringify(r)}: ac.newRole({ project: ["read", "update"] }),`).join("\n")}
};
`;
}

export function smsFile(): string {
  return `// Generated once by \`boilauth init\`. Yours to edit: connect your SMS provider here.
import type { SmsMessage } from "boilauth";

export async function sendSms(msg: SmsMessage): Promise<void> {
  if (process.env.NODE_ENV === "production") {
    throw new Error("src/sms.ts: connect an SMS provider before production");
  }
  console.log(\`[sms to \${msg.to}] \${msg.text}\`);
}
`;
}

export function emailFile(): string {
  return `// Generated once by \`boilauth init\`. Yours to edit: connect your mail provider here.
import type { EmailMessage } from "boilauth";

// msg.kind is set on security notices (security.password_changed, security.mfa_changed,
// security.account_locked, security.new_device) if you want your own templates for them.
export async function sendEmail(msg: EmailMessage): Promise<void> {
  if (process.env.NODE_ENV === "production") {
    throw new Error("src/email.ts: connect a mail provider before production");
  }
  console.log(\`[email to \${msg.to}] \${msg.subject}\\n\${msg.text}\`);
}
`;
}

export function deletionGuardFile(): string {
  return `// Generated once by \`boilauth init\` (deletion.guard). Yours to edit: init leaves it alone once it exists.
// Called before every self-service deletion. Refusing answers 409 with your code and changes nothing.
import type { DeletionCheck } from "boilauth/deletion";

export const canDelete: DeletionCheck = async (user) => {
  // Example: keep the account while a paid subscription is active.
  // if (await hasActiveSubscription(user.id)) {
  //   return { ok: false, code: "active_subscription", message: "Cancel the subscription before deleting the account" };
  // }
  void user;
  return { ok: true };
};
`;
}
