/** Files written by `boilauth init`. */

export const CONFIG_TEMPLATE = `// boilauth.config.mjs — generated by \`boilauth init\`.
// The CLI imports this file; your app can import the same instance.
import { DatabaseSync } from "node:sqlite";
import { createBoilAuth } from "boilauth";

// Postgres instead of SQLite:
//   import pg from "pg";
//   const database = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const database = new DatabaseSync(process.env.BOILAUTH_SQLITE ?? "auth.db");

if (!process.env.BOILAUTH_SECRET) throw new Error("set BOILAUTH_SECRET (32+ random bytes)");

export default createBoilAuth({
  database,
  secret: process.env.BOILAUTH_SECRET,
  baseURL: process.env.BOILAUTH_URL ?? "http://localhost:3000",
  // Only if you import from Firebase: Console → Authentication → Users →
  // ⋮ → Password hash parameters. Keep the signer key in env, not in git.
  // firebaseKeys: [{
  //   keyId: "my-firebase-project",
  //   signerKey: process.env.FIREBASE_SIGNER_KEY,
  //   saltSeparator: "Bw==",
  //   rounds: 8,
  //   memCost: 14,
  // }],
});
`;

export const ENV_TEMPLATE = `# openssl rand -base64 32
BOILAUTH_SECRET=
BOILAUTH_URL=http://localhost:3000
BOILAUTH_SQLITE=auth.db
# FIREBASE_SIGNER_KEY=
`;
